---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# macrobd

<!-- badges: start -->
<!-- badges: end -->

The goal of macrobd is to ...

## Installation

You can install the released version of macrobd from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("macrobd")
```

## Example


# Some analysis


```{r}
library(patchwork)
money.ts <- as.tsibble(money)

money.ts %>% 
    filter_index("2018" ~ .) %>% 
    ggplot() + geom_line(aes(date, M1,group=""))

deposit.ts  <- as.tsibble(deposit)

deposit.dd <- deposit.ts %>% 
    filter_index("2018" ~ .) %>% 
    ggplot() + 
       geom_line(aes(date,dp.dd,group=""))


deposit.td <- deposit.ts %>% 
    filter_index("2018" ~ .) %>% 
    ggplot() + 
       geom_line(aes(date,dp.td,group=""), color="blue") 
deposit.dd + deposit.td
```



